// -*- tab-width:2 -*-

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// loadSummary reads a summary JSON document written by `summarize`.
func loadSummary(path string) (summary, error) {
	var s summary

	b, err := os.ReadFile(path)
	if err != nil {
		return s, err
	}

	if err := json.Unmarshal(b, &s); err != nil {
		return s, err
	}

	return s, nil
}

// loadOrDie loads a summary or prints an error and exits.
func loadOrDie(flagName, path string) summary {
	s, err := loadSummary(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading %s (%s): %v\n", flagName, path, err)
		os.Exit(exitErr)
	}

	return s
}

// ancestors returns the relative paths that strictly contain rel, from
// the root (".") down to rel's parent.  rel "." has no ancestors.
func ancestors(rel string) []string {
	if rel == "." || rel == "" {
		return nil
	}

	segs := strings.Split(rel, "/")
	res := []string{"."}

	for i := 1; i < len(segs); i++ {
		res = append(res, strings.Join(segs[:i], "/"))
	}

	return res
}

type reclaim struct {
	cand     dirSummary
	havePath string
}

// isCovered reports whether some ancestor of rel is also removable, in
// which case deleting that ancestor already reclaims rel.
func isCovered(rel string, removable map[string]struct{}) bool {
	for _, a := range ancestors(rel) {
		if _, ok := removable[a]; ok {
			return true
		}
	}

	return false
}

// findReclaims returns the maximal candidate directories whose entire
// content already lives on the keep side (largest first).
func findReclaims(have, cand summary, minSize int64) []reclaim {
	// hash -> an example path on the keep side
	haveHashes := make(map[string]string, len(have.Dirs))
	for _, d := range have.Dirs {
		if _, ok := haveHashes[d.Hash]; !ok {
			haveHashes[d.Hash] = d.Path
		}
	}

	// every candidate dir whose whole subtree exists on the keep side
	removable := make(map[string]struct{})
	hits := []reclaim{}

	for _, d := range cand.Dirs {
		hp, ok := haveHashes[d.Hash]
		if !ok || d.Size < minSize {
			continue
		}

		removable[d.Rel] = struct{}{}

		hits = append(hits, reclaim{cand: d, havePath: hp})
	}

	// keep only maximal matches (drop dirs covered by a removable ancestor)
	maximal := []reclaim{}

	for _, h := range hits {
		if !isCovered(h.cand.Rel, removable) {
			maximal = append(maximal, h)
		}
	}

	sort.Slice(maximal, func(i, j int) bool {
		return maximal[i].cand.Size > maximal[j].cand.Size
	})

	return maximal
}

// doCompare finds directories in the candidate tree whose content is
// already present in the have tree, and reports the largest removable
// ones (with no double counting of nested matches).  topN and minSize
// come from config.txt.
func doCompare(have, cand summary) {
	maximal := findReclaims(have, cand, int64(cfgInt("minSize")))

	printReclaim(cand.Root, have.Root, maximal, cfgInt("topN"))

	if script := cfgStr("deleteScript"); script != "" && len(maximal) > 0 {
		if err := writeDeleteScript(script, cand.Root, have.Root, maximal); err != nil {
			g.Ml.La("Error writing delete script", script, err)
		} else {
			g.Ml.La("Wrote", len(maximal), "rm commands to", script)
			fmt.Printf("\nWrote shell script %s (review before running).\n", script)
		}
	}
}

// shellSingleQuote wraps s in single quotes so /bin/sh treats it as one
// literal argument, escaping any embedded single quote as the usual
// '\” sequence.  Safe for any path that does not contain a newline.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// deleteScriptPerm is the mode for the generated script: executable so it
// can be run directly, but the -rI in every rm is the real safety net.
const deleteScriptPerm = 0o755

// writeDeleteScript writes a runnable shell script that removes every
// reclaimable candidate directory.  Each path is single-quoted and rm
// uses -rI, which asks once for confirmation before each recursive
// delete -- far less tedious than -i (which prompts per file) but still
// a deliberate "are you sure?".  The file is named dangerous on purpose:
// running it deletes data.
func writeDeleteScript(path, candRoot, haveRoot string, maximal []reclaim) error {
	var total int64
	for _, h := range maximal {
		total += h.cand.Size
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "#!/bin/sh")
	fmt.Fprintln(f, "#")
	fmt.Fprintf(f, "# DANGEROUS: this script DELETES directories from %s.\n", candRoot)
	fmt.Fprintln(f, "# Every directory below has contents already present on the keep")
	fmt.Fprintf(f, "# side (%s), so removing it reclaims space without losing data.\n", haveRoot)
	fmt.Fprintln(f, "# Generated by summarizeFsTrees -- REVIEW before running.")
	fmt.Fprintf(f, "# Total reclaimable: %s across %d directories.\n", humanize(total), len(maximal))
	fmt.Fprintln(f, "#")
	fmt.Fprintln(f, "# 'rm -rI' asks once for confirmation before each recursive delete.")
	fmt.Fprintln(f, "")

	for _, h := range maximal {
		msg := fmt.Sprintf("%s, %d files (already at %s)",
			humanize(h.cand.Size), h.cand.Files, h.havePath)
		fmt.Fprintf(f, "echo %s\n", shellSingleQuote(msg))
		fmt.Fprintf(f, "rm -rI %s\n", shellSingleQuote(h.cand.Path))
	}

	if err := f.Chmod(deleteScriptPerm); err != nil {
		return err
	}

	return f.Close()
}

func printReclaim(candRoot, haveRoot string, maximal []reclaim, top int) {
	var total int64
	for _, h := range maximal {
		total += h.cand.Size
	}

	fmt.Printf("Candidate tree: %s\n", candRoot)
	fmt.Printf("Compared against: %s\n\n", haveRoot)

	if len(maximal) == 0 {
		fmt.Println("No directories in the candidate tree are fully duplicated on the keep side.")

		return
	}

	fmt.Printf("Removable directories (content already present on the keep side), largest first:\n\n")
	fmt.Printf("%12s  %9s  %s\n", "SIZE", "FILES", "CANDIDATE DIR  ->  ALREADY AT")

	shown := maximal
	if len(shown) > top {
		shown = shown[:top]
	}

	for _, h := range shown {
		fmt.Printf("%12s  %9d  %s  ->  %s\n",
			humanize(h.cand.Size), h.cand.Files, h.cand.Path, h.havePath)
	}

	if len(maximal) > len(shown) {
		fmt.Printf("\n... and %d more not shown (raise -top to see them).\n", len(maximal)-len(shown))
	}

	fmt.Printf("\nTotal reclaimable: %s across %d directories.\n", humanize(total), len(maximal))
}

// doCompareFiles does the directory-level compare AND, using the per-file
// md5s that emitFiles records, additionally finds "loose" duplicate
// files: files whose contents already exist somewhere on the keep side
// but that are NOT inside a fully-duplicated directory (so the plain
// compare misses them).  topN/minSize/deleteScript come from config.txt.
func doCompareFiles(have, cand summary) {
	minSize := int64(cfgInt("minSize"))
	top := cfgInt("topN")

	maximal := findReclaims(have, cand, minSize)
	printReclaim(cand.Root, have.Root, maximal, top)

	if len(have.Files) == 0 || len(cand.Files) == 0 {
		fmt.Println("\nNo per-file data in one or both summaries -- re-run summarize")
		fmt.Println("with emitFiles=true on BOTH sides to get the loose-file report.")

		return
	}

	loose := findLooseFiles(have, cand, maximal, minSize)
	printLooseFiles(loose, top)

	var dirTotal, looseTotal int64

	for _, h := range maximal {
		dirTotal += h.cand.Size
	}

	for _, f := range loose {
		looseTotal += f.Size
	}

	fmt.Printf("\nGRAND TOTAL reclaimable (directories + loose files): %s\n",
		humanize(dirTotal+looseTotal))

	if script := cfgStr("deleteScript"); script != "" && (len(maximal) > 0 || len(loose) > 0) {
		if err := writeDeleteScriptFiles(script, cand.Root, have.Root, maximal, loose); err != nil {
			g.Ml.La("Error writing delete script", script, err)
		} else {
			g.Ml.La("Wrote delete script", script)
			fmt.Printf("\nWrote shell script %s (review before running).\n", script)
		}
	}
}

// findLooseFiles returns candidate files whose contents exist on the keep
// side but which are not inside any already-reclaimable directory, sorted
// largest first.
func findLooseFiles(have, cand summary, maximal []reclaim, minSize int64) []fileSummary {
	haveHashes := make(map[string]struct{}, len(have.Files))
	for _, f := range have.Files {
		haveHashes[f.Hash] = struct{}{}
	}

	// rels of the reclaimable dirs, so files already covered by a whole-dir
	// match are not counted again.
	covered := make(map[string]struct{}, len(maximal))
	for _, h := range maximal {
		covered[h.cand.Rel] = struct{}{}
	}

	var loose []fileSummary

	for _, f := range cand.Files {
		if f.Size < minSize || isCovered(f.Rel, covered) {
			continue
		}

		if _, ok := haveHashes[f.Hash]; ok {
			loose = append(loose, f)
		}
	}

	sort.Slice(loose, func(i, j int) bool {
		return loose[i].Size > loose[j].Size
	})

	return loose
}

func printLooseFiles(loose []fileSummary, top int) {
	var total int64
	for _, f := range loose {
		total += f.Size
	}

	fmt.Printf("\nLoose duplicate files (content already on the keep side, not inside\n")
	fmt.Printf("any fully-duplicated directory), largest first:\n\n")

	if len(loose) == 0 {
		fmt.Println("  (none)")

		return
	}

	fmt.Printf("%12s  %s\n", "SIZE", "CANDIDATE FILE")

	shown := loose
	if len(shown) > top {
		shown = shown[:top]
	}

	for _, f := range shown {
		fmt.Printf("%12s  %s\n", humanize(f.Size), f.Path)
	}

	if len(loose) > len(shown) {
		fmt.Printf("\n... and %d more not shown (raise topN).\n", len(loose)-len(shown))
	}

	fmt.Printf("\nLoose-file reclaimable: %s across %d files.\n", humanize(total), len(loose))
}

// writeDeleteScriptFiles writes a runnable shell script that removes both
// the fully-duplicated directories (rm -rI) and the loose duplicate files
// (rm -I).  Like writeDeleteScript, it is meant to be reviewed first.
func writeDeleteScriptFiles(path, candRoot, haveRoot string, maximal []reclaim, loose []fileSummary) error {
	var total int64

	for _, h := range maximal {
		total += h.cand.Size
	}

	for _, lf := range loose {
		total += lf.Size
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "#!/bin/sh")
	fmt.Fprintln(f, "#")
	fmt.Fprintf(f, "# DANGEROUS: this script DELETES data from %s.\n", candRoot)
	fmt.Fprintf(f, "# Everything below already exists on the keep side (%s).\n", haveRoot)
	fmt.Fprintln(f, "# Generated by summarizeFsTrees compare-files -- REVIEW before running.")
	fmt.Fprintf(f, "# Total reclaimable: %s (%d dirs, %d loose files).\n",
		humanize(total), len(maximal), len(loose))
	fmt.Fprintln(f, "#")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "# --- fully-duplicated directories (rm -rI: confirm once each) ---")

	for _, h := range maximal {
		msg := fmt.Sprintf("%s, %d files (already at %s)",
			humanize(h.cand.Size), h.cand.Files, h.havePath)
		fmt.Fprintf(f, "echo %s\n", shellSingleQuote(msg))
		fmt.Fprintf(f, "rm -rI %s\n", shellSingleQuote(h.cand.Path))
	}

	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "# --- loose duplicate files ---")

	for _, lf := range loose {
		fmt.Fprintf(f, "rm -I %s\n", shellSingleQuote(lf.Path))
	}

	if err := f.Chmod(deleteScriptPerm); err != nil {
		return err
	}

	return f.Close()
}
