// -*- tab-width:2 -*-

package main

import (
	"fmt"
	"os"
	"sort"
)

// minDupCopies is the smallest group size that counts as a duplicate.
const minDupCopies = 2

// dupGroup is a set of 2+ directories within ONE tree that have identical
// content (same recursive hash).  Keeping one copy and deleting the rest
// reclaims Reclaim bytes.
type dupGroup struct {
	size    int64
	dirs    []dirSummary
	reclaim int64
}

// buildDupSet returns the rels of every directory that is part of some
// duplicate set, used to drop nested (lower-level) groups.
func buildDupSet(byHash map[string][]dirSummary) map[string]struct{} {
	dupSet := make(map[string]struct{})

	for _, ds := range byHash {
		if len(ds) < minDupCopies {
			continue
		}

		for _, d := range ds {
			dupSet[d.Rel] = struct{}{}
		}
	}

	return dupSet
}

// groupIsNested reports whether any member of the group has a strict
// ancestor that is itself a duplicated directory (so deleting that outer
// copy already removes this one -- report the outer group instead).
func groupIsNested(ds []dirSummary, dupSet map[string]struct{}) bool {
	for _, d := range ds {
		for _, a := range ancestors(d.Rel) {
			if _, ok := dupSet[a]; ok {
				return true
			}
		}
	}

	return false
}

// findSelfDups groups the summary's directories by content hash and
// returns the duplicate groups that sit at the highest level, largest
// reclaim first.  Empty and below-minSize groups are skipped.
func findSelfDups(sum summary, minSize int64) []dupGroup {
	byHash := make(map[string][]dirSummary)
	for _, d := range sum.Dirs {
		byHash[d.Hash] = append(byHash[d.Hash], d)
	}

	dupSet := buildDupSet(byHash)

	groups := make([]dupGroup, 0, len(byHash))

	for _, ds := range byHash {
		size := ds[0].Size
		if len(ds) < minDupCopies || size == 0 || size < minSize || groupIsNested(ds, dupSet) {
			continue
		}

		sort.Slice(ds, func(i, j int) bool { return ds[i].Path < ds[j].Path })

		groups = append(groups, dupGroup{
			size:    size,
			dirs:    ds,
			reclaim: int64(len(ds)-1) * size,
		})
	}

	sort.Slice(groups, func(i, j int) bool {
		if groups[i].reclaim != groups[j].reclaim {
			return groups[i].reclaim > groups[j].reclaim
		}

		return groups[i].dirs[0].Path < groups[j].dirs[0].Path
	})

	return groups
}

// reportSelfDups prints the intra-tree duplicate directory groups and, if
// deleteScript is set, writes a script that keeps one copy of each.
func reportSelfDups(sum summary) {
	groups := findSelfDups(sum, int64(cfgInt("minSize")))

	fmt.Printf("Tree: %s\n\n", sum.Root)

	if len(groups) == 0 {
		fmt.Println("No duplicate directories found within the tree.")

		return
	}

	var total int64
	for _, gr := range groups {
		total += gr.reclaim
	}

	fmt.Printf("Duplicate directory groups within the tree (highest level, most\n")
	fmt.Printf("reclaimable first).  Keep one copy of each, delete the rest:\n\n")

	printDupGroups(groups, cfgInt("topN"))

	fmt.Printf("Total reclaimable by keeping one copy of each: %s across %d groups.\n",
		humanize(total), len(groups))

	if script := cfgStr("deleteScript"); script != "" {
		if err := writeSelfDupsScript(script, sum.Root, groups); err != nil {
			g.Ml.La("Error writing delete script", script, err)
		} else {
			g.Ml.La("Wrote delete script", script)
			fmt.Printf("\nWrote shell script %s (review before running).\n", script)
		}
	}
}

func printDupGroups(groups []dupGroup, top int) {
	shown := groups
	if len(shown) > top {
		shown = shown[:top]
	}

	for _, gr := range shown {
		fmt.Printf("  reclaim %s  (%s each x %d copies)\n",
			humanize(gr.reclaim), humanize(gr.size), len(gr.dirs))

		for i, d := range gr.dirs {
			tag := "<- redundant copy"
			if i == 0 {
				tag = "(keep)"
			}

			fmt.Printf("      %s  %s\n", d.Path, tag)
		}

		fmt.Println()
	}

	if len(groups) > len(shown) {
		fmt.Printf("... and %d more groups not shown (raise topN).\n\n", len(groups)-len(shown))
	}
}

// writeSelfDupsScript writes a runnable shell script that keeps the first
// directory of each group and removes the rest (rm -rI).  Meant to be
// reviewed before running.
func writeSelfDupsScript(path, root string, groups []dupGroup) error {
	var total int64
	for _, gr := range groups {
		total += gr.reclaim
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "#!/bin/sh")
	fmt.Fprintln(f, "#")
	fmt.Fprintf(f, "# DANGEROUS: this script DELETES redundant copies within %s.\n", root)
	fmt.Fprintln(f, "# Each group is a set of byte-identical directories; the first is")
	fmt.Fprintln(f, "# kept and the rest removed.  Generated by summarizeFsTrees.")
	fmt.Fprintf(f, "# Total reclaimable: %s across %d groups.\n", humanize(total), len(groups))
	fmt.Fprintln(f, "#")
	fmt.Fprintln(f, "# 'rm -rI' asks once for confirmation before each recursive delete.")
	fmt.Fprintln(f, "")

	for _, gr := range groups {
		fmt.Fprintf(f, "# keep: %s\n", shellSingleQuote(gr.dirs[0].Path))

		for _, d := range gr.dirs[1:] {
			msg := fmt.Sprintf("%s (dup of %s)", humanize(gr.size), gr.dirs[0].Path)
			fmt.Fprintf(f, "echo %s\n", shellSingleQuote(msg))
			fmt.Fprintf(f, "rm -rI %s\n", shellSingleQuote(d.Path))
		}

		fmt.Fprintln(f, "")
	}

	if err := f.Chmod(deleteScriptPerm); err != nil {
		return err
	}

	return f.Close()
}
